"""Misorientation distribution functions (MDF) and random baselines.

`MisorientationDistribution` collects symmetry-reduced disorientation angles
from an orientation population, either *uncorrelated* (all unique pairs) or
*correlated* (an explicit set of neighbour/boundary pairs), and exposes angle
statistics and histograms.

The random baseline is the distribution of disorientation angles between
independent, uniformly (Haar) distributed orientations reduced by the crystal
point group -- the sampled analogue of the Mackenzie distribution. It is
generated by seeded Monte-Carlo sampling so results are reproducible.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from numpy.typing import ArrayLike

from pytex.core.orientation import OrientationSet, quaternions_to_matrices
from pytex.core.symmetry import SymmetrySpec


def _reduced_disorientation_deg(
    relative_matrices: np.ndarray,
    operators: np.ndarray,
) -> np.ndarray:
    """Symmetry-reduced disorientation angle of each relative rotation.

    Returns ``min over S_a, S_b of angle(S_a @ M @ S_b)`` per matrix ``M``.
    """

    if relative_matrices.shape[0] == 0:
        return np.empty(0, dtype=np.float64)
    left = np.einsum("aij,sjk->saik", operators, relative_matrices, optimize=True)
    products = np.einsum("saij,bjk->sabik", left, operators, optimize=True)
    traces = np.trace(products, axis1=3, axis2=4)
    cos_theta = np.clip((traces - 1.0) * 0.5, -1.0, 1.0)
    angles = np.arccos(cos_theta)
    minimum = np.min(angles.reshape(relative_matrices.shape[0], -1), axis=1)
    return np.asarray(np.degrees(minimum), dtype=np.float64)


def _operators_for(symmetry: SymmetrySpec | None) -> np.ndarray:
    if symmetry is None:
        return np.eye(3, dtype=np.float64)[None, :, :]
    return np.asarray(symmetry.operators, dtype=np.float64)


def _haar_uniform_quaternions(count: int, rng: np.random.Generator) -> np.ndarray:
    """Uniformly distributed unit quaternions (Shoemake's method)."""

    u1, u2, u3 = rng.random(count), rng.random(count), rng.random(count)
    root1 = np.sqrt(1.0 - u1)
    root2 = np.sqrt(u1)
    return np.column_stack(
        [
            root1 * np.sin(2.0 * np.pi * u2),
            root1 * np.cos(2.0 * np.pi * u2),
            root2 * np.sin(2.0 * np.pi * u3),
            root2 * np.cos(2.0 * np.pi * u3),
        ]
    )


def random_disorientation_angles_deg(
    symmetry: SymmetrySpec | None,
    count: int,
    *,
    seed: int = 0,
) -> np.ndarray:
    """Disorientation angles of ``count`` random misorientations under ``symmetry``."""

    if count <= 0:
        raise ValueError("count must be strictly positive.")
    rng = np.random.default_rng(seed)
    quaternions = _haar_uniform_quaternions(count, rng)
    matrices = quaternions_to_matrices(quaternions)
    return _reduced_disorientation_deg(matrices, _operators_for(symmetry))


@dataclass(frozen=True, slots=True)
class MisorientationDistribution:
    """A population of misorientation angles, for boundary statistics.

    Purpose
    -------
    The misorientation-angle distribution of a grain-boundary network. Its
    comparison against the Mackenzie distribution — the analytic
    misorientation distribution of a randomly textured aggregate — is the
    standard test for whether boundaries formed preferentially, as in
    twinning or variant selection.

    Attributes
    ----------
    angles_deg : np.ndarray
        Misorientation angles in degrees, usually symmetry-reduced
        disorientation angles.
    provenance : ProvenanceRecord, optional
    """

    angles_deg: np.ndarray
    symmetry: SymmetrySpec | None = None
    correlated: bool = False

    def __post_init__(self) -> None:
        angles = np.ascontiguousarray(np.asarray(self.angles_deg, dtype=np.float64))
        if angles.ndim != 1:
            raise ValueError("MisorientationDistribution.angles_deg must be a 1D array.")
        angles.setflags(write=False)
        object.__setattr__(self, "angles_deg", angles)

    @property
    def count(self) -> int:
        """Number of misorientation angles in the distribution.
        """

        return int(self.angles_deg.size)

    @property
    def mean_angle_deg(self) -> float:
        """Mean misorientation angle in degrees; ``0.0`` when empty.

        Compare it against the Mackenzie value for a randomly textured aggregate
        — about 40.7 degrees for cubic symmetry — to judge whether the boundary
        population departs from random. Note that the Mackenzie distribution's
        *mode* sits near 45 degrees while its mean is lower, because the
        distribution is left-skewed: a long low-angle tail pulls the mean down
        while the hard cutoff at 62.8 degrees stops the other side compensating.
        Quoting 45 degrees as the mean conflates the two.
        """

        return float(np.mean(self.angles_deg)) if self.count else 0.0

    @property
    def max_angle_deg(self) -> float:
        """Largest misorientation angle in degrees; ``0.0`` when empty.

        For symmetry-reduced (disorientation) angles this is bounded by the
        symmetry's maximum disorientation: 62.8 degrees for cubic-cubic.
        """

        return float(np.max(self.angles_deg)) if self.count else 0.0

    def histogram(
        self,
        *,
        bins: int = 36,
        angle_range: tuple[float, float] | None = None,
        density: bool = True,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Histogram of the misorientation angles.

        Purpose
        -------
        The misorientation-angle distribution, whose comparison against the
        Mackenzie random-texture distribution is the standard test for
        preferential boundary formation — twinning, variant selection, or
        texture-driven correlation.

        Parameters
        ----------
        bins : int
            Number of bins.
        angle_range : tuple of float, optional
            ``(lower, upper)`` in degrees. Defaults to zero through the observed
            maximum. Fix it explicitly when comparing several distributions, or
            the bin edges will differ between them.
        density : bool
            Normalize to a probability density (default), which is what makes
            the comparison against Mackenzie meaningful.

        Returns
        -------
        tuple of np.ndarray
            Counts (or densities) and bin edges, as from ``numpy.histogram``.

        Raises
        ------
        ValueError
            When the distribution is empty.
        """

        if self.count == 0:
            raise ValueError("Cannot histogram an empty MisorientationDistribution.")
        upper = angle_range[1] if angle_range is not None else float(np.max(self.angles_deg))
        lower = angle_range[0] if angle_range is not None else 0.0
        counts, edges = np.histogram(
            self.angles_deg, bins=bins, range=(lower, upper), density=density
        )
        return np.asarray(counts, dtype=np.float64), np.asarray(edges, dtype=np.float64)

    @classmethod
    def from_orientations(
        cls,
        orientations: OrientationSet,
        *,
        pairs: ArrayLike | None = None,
        symmetry_aware: bool = True,
    ) -> MisorientationDistribution:
        """Build an MDF from an orientation population.

        With ``pairs=None`` the uncorrelated distribution over all unique index
        pairs is used; passing an ``(m, 2)`` array of index pairs (for example
        grain-boundary neighbours) yields the correlated distribution.
        """

        matrices = orientations.as_matrices()
        if pairs is None:
            left_idx, right_idx = np.triu_indices(len(orientations), k=1)
            correlated = False
        else:
            pair_array = np.asarray(pairs, dtype=np.int64)
            if pair_array.ndim != 2 or pair_array.shape[1] != 2:
                raise ValueError("pairs must have shape (m, 2).")
            left_idx, right_idx = pair_array[:, 0], pair_array[:, 1]
            correlated = True
        # Crystal-frame relative rotation inv(o_i) @ o_j = R_i^T @ R_j.
        relative = np.einsum(
            "sji,sjk->sik", matrices[left_idx], matrices[right_idx], optimize=True
        )
        operators = (
            _operators_for(orientations.symmetry)
            if symmetry_aware
            else np.eye(3, dtype=np.float64)[None, :, :]
        )
        angles = _reduced_disorientation_deg(relative, operators)
        return cls(angles_deg=angles, symmetry=orientations.symmetry, correlated=correlated)

    @classmethod
    def random_baseline(
        cls,
        symmetry: SymmetrySpec | None,
        *,
        count: int = 2000,
        seed: int = 0,
    ) -> MisorientationDistribution:
        """The random (Mackenzie-type) baseline distribution for a point group."""

        angles = random_disorientation_angles_deg(symmetry, count, seed=seed)
        return cls(angles_deg=angles, symmetry=symmetry, correlated=False)


__all__ = [
    "MisorientationDistribution",
    "random_disorientation_angles_deg",
]
