"""The Kearns parameter: one number for the basal texture, by every route.

What it does
    Computes the Kearns orientation parameter ``f`` — the effective fraction of
    basal poles aligned with a specimen direction — by the routes the zirconium
    literature actually uses: from discrete orientations, from a theta-2theta
    diffractogram, and from a basal-pole tilt profile. Every route reports the
    same object, so three independent measurements of one specimen can be put
    beside each other and compared.

Why the routes are separate operations rather than one with a mode switch
    They take genuinely different data and carry genuinely different systematic
    errors. A diffractogram needs a random-powder reference and gives one
    direction per section; an orientation set needs none and gives the whole
    triad at once. Hiding that behind a single form would suggest the inputs are
    interchangeable, which is the mistake this panel exists to prevent.

The check that matters more than the number
    For any orthonormal specimen triad, ``f_RD + f_TD + f_ND = 1`` exactly, for
    every texture — it is the trace of a second-moment tensor of unit vectors,
    not an empirical regularity. So a triad that does not sum to 1 measures the
    systematic error of the *measurement*: an unmeasured tilt range, a wrong
    random standard, an unbalanced background. The panel shows the sum wherever
    it applies and says what a departure means, because a Kearns parameter
    quoted without it is a number nobody can check.

The defaults are synthetic, and say so
    The default inputs are the diffraction peaks and tilt profile of a **known**
    basal fibre texture, generated by the recipe in
    ``tests/unit/test_kearns_parameter.py``. That is deliberate and follows the
    texture panel's own principle: the answer is known before the calculation
    runs, so pressing the button without touching a control demonstrates the
    method against a truth rather than against an opinion. All three routes
    return the same ``f_ND`` on those defaults, which is the point.

See ``docs/site/theory/kearns_parameter_and_basal_pole_texture.md`` for the
derivation and the literature.
"""

from __future__ import annotations

import math
from typing import Any

import numpy as np

from pytex.app.errors import InvalidInputError
from pytex.app.phases import PhaseSpec, phase_from_request
from pytex.app.registry import (
    REGISTRY,
    BooleanParameter,
    ChoiceParameter,
    ExampleScenario,
    NumberParameter,
    TextParameter,
)
from pytex.app.results import AppResult, Column, ResultTable
from pytex.app.services.calculator import phase_parameter

__all__: tuple[str, ...] = ()

_CITATION_KEARNS = (
    "J. J. Kearns, Thermal expansion and preferred orientation in Zircaloy, "
    "WAPD-TM-472, Bettis Atomic Power Laboratory (1965), Eqs. (1)-(7) and Table 3."
)
_CITATION_BARON = (
    "J. L. Baron et al., Textures and Microstructures 12 (1990) 125-140, "
    "doi:10.1155/TSM.12.125 (the pole-figure route and its pseudo-norm)."
)
_CITATION_MANI = (
    "K. V. Mani Krishna et al., J. Nucl. Mater. 414 (2011) 492-497, "
    "doi:10.1016/j.jnucmat.2011.04.065 (comparison of the routes)."
)
_CITATION_HOLT = (
    "R. A. Holt and S. A. Aldridge, J. Nucl. Mater. 135 (1985) 246-259 "
    "(the resolved-basal-pole form used in the pressure-tube literature)."
)

#: The specimen frame of this panel, shared with the texture panel so a Kearns
#: parameter and a pole figure of the same specimen are read in one frame.
_SPECIMEN_AXES = ("RD", "TD", "ND")

#: The Kearns parameter of an untextured aggregate, in every direction. Quoted
#: beside every result as the null hypothesis a measured ``f`` is read against.
_ISOTROPIC = 1.0 / 3.0

#: Which specimen direction a single-section route reports ``f`` along.
_DIRECTION_OPTIONS = (
    (
        "ND",
        "ND (normal direction)",
        "The sheet or plate normal — the section a symmetric scan of a rolled product measures.",
    ),
    ("RD", "RD (rolling direction)", "The rolling, extrusion, or drawing direction."),
    ("TD", "TD (transverse direction)", "The transverse direction."),
)

_DIRECTION_VECTORS = {
    "RD": (1.0, 0.0, 0.0),
    "TD": (0.0, 1.0, 0.0),
    "ND": (0.0, 0.0, 1.0),
}

#: The default diffractogram: the peaks a symmetric scan would record from a
#: basal fibre of 30 degree spread about ND. Generated by the
#: ``synthetic_reflections`` recipe of ``tests/unit/test_kearns_parameter.py``,
#: whose true ``f_ND`` is 0.6423 — so the route can be seen recovering it.
_DEFAULT_REFLECTIONS = """\
# Synthetic alpha-Zr section: a basal fibre 30 deg about ND, true f_ND = 0.642.
# plane (h k i l)   intensity   random-powder intensity
0 0 0 2    4.432   1.0
1 0 -1 5   3.158   1.0
1 0 -1 4   2.858   1.0
1 0 -1 3   2.292   1.0
2 0 -2 5   1.935   1.0
1 0 -1 2   1.462   1.0
2 0 -2 3   0.938   1.0
1 1 -2 2   0.648   1.0
1 0 -1 1   0.475   1.0
2 1 -3 2   0.309   1.0
2 0 -2 1   0.176   1.0
2 1 -3 1   0.130   1.0
1 0 -1 0   0.048   1.0
"""

#: The default tilt profile: the same synthetic texture, azimuthally averaged
#: onto Kearns' own 10 degree bin midpoints.
_DEFAULT_TILT_PROFILE = """\
# Synthetic alpha-Zr basal fibre, 30 deg about ND; true f_ND = 0.642.
# tilt from ND (deg)   azimuthally averaged basal-pole density
5    3.920
15   3.521
25   2.799
35   2.032
45   1.299
55   0.757
65   0.387
75   0.180
85   0.073
"""


def _specimen_frame() -> Any:
    from pytex.core import FrameDomain, Handedness, ReferenceFrame

    return ReferenceFrame(
        name="specimen",
        domain=FrameDomain.SPECIMEN,
        axes=_SPECIMEN_AXES,
        handedness=Handedness.RIGHT,
    )


def _basal_pole(phase: Any) -> Any:
    """The ``(0002)`` plane of a hexagonal phase, refused for anything else.

    Refused rather than silently generalized: the machinery answers the question
    for any pole, but the *Kearns parameter* is defined on the basal pole of a
    hexagonal crystal, and a number computed from ``(002)`` of a cubic phase
    would be a valid second moment carrying an invalid name.
    """

    from pytex.core.hexagonal import is_hexagonal_phase
    from pytex.core.lattice import CrystalPlane

    if not is_hexagonal_phase(phase):
        raise InvalidInputError(
            f"The Kearns parameter is defined for hexagonal phases; {phase.name} is not one.",
            field="phase",
            hint=(
                "Choose a hexagonal phase — alpha-Zr, alpha-Ti, or Mg are in the catalogue. The "
                "parameter resolves the basal (0002) pole, which a cubic phase does not have."
            ),
        )
    return CrystalPlane.from_miller_bravais((0, 0, 0, 2), phase=phase)


def _data_lines(text: str, *, field: str) -> list[tuple[int, list[str]]]:
    """Split a pasted block into numbered, comment-free, tokenized rows.

    Comments after ``#`` and blank lines are dropped, and the original line
    number travels with each row so an error can name the line the user is
    looking at rather than the index of a filtered list.
    """

    rows: list[tuple[int, list[str]]] = []
    for number, raw in enumerate(str(text or "").splitlines(), start=1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        rows.append((number, line.replace(",", " ").split()))
    if not rows:
        raise InvalidInputError(
            "No data rows were given.",
            field=field,
            hint="Every line was blank or a comment. One measurement per line.",
        )
    return rows


def _number(token: str, *, line: int, field: str, what: str) -> float:
    try:
        value = float(token)
    except ValueError as error:
        raise InvalidInputError(
            f"Line {line}: '{token}' is not a number, and {what} must be.",
            field=field,
        ) from error
    if not math.isfinite(value):
        raise InvalidInputError(f"Line {line}: {what} must be finite.", field=field)
    return value


def _parse_reflections(text: str, *, phase: Any) -> list[Any]:
    """Parse the reflection block into `DiffractogramReflection` objects.

    Each line is ``h k i l  intensity  [random intensity]``. The four-index
    Miller-Bravais form is required rather than three-index, because the whole
    method turns on each reflection's tilt to ``[0001]`` and the four-index form
    is how that plane is named in every table the intensities will be read
    against.
    """

    from pytex.core.lattice import CrystalPlane
    from pytex.texture.kearns import DiffractogramReflection

    reflections: list[Any] = []
    for line, tokens in _data_lines(text, field="reflections"):
        if len(tokens) not in (5, 6):
            raise InvalidInputError(
                f"Line {line} has {len(tokens)} values; a reflection needs 5 or 6.",
                field="reflections",
                hint=(
                    "Write the plane as four Miller-Bravais indices, then the measured "
                    "intensity, then the random-powder intensity: `1 0 -1 3  2.292  1.0`."
                ),
            )
        indices = []
        for token in tokens[:4]:
            try:
                indices.append(int(token))
            except ValueError as error:
                raise InvalidInputError(
                    f"Line {line}: '{token}' is not a whole number, and a Miller-Bravais "
                    "index must be.",
                    field="reflections",
                ) from error
        if indices[0] + indices[1] + indices[2] != 0:
            raise InvalidInputError(
                f"Line {line}: Miller-Bravais indices must satisfy h + k + i = 0; "
                f"{indices[0]} + {indices[1]} + {indices[2]} = "
                f"{indices[0] + indices[1] + indices[2]}.",
                field="reflections",
                hint="The third index is not free: i = -(h + k).",
            )
        intensity = _number(tokens[4], line=line, field="reflections", what="an intensity")
        random_intensity = (
            _number(tokens[5], line=line, field="reflections", what="a random intensity")
            if len(tokens) == 6
            else 1.0
        )
        if intensity < 0.0:
            raise InvalidInputError(
                f"Line {line}: an integrated intensity cannot be negative.",
                field="reflections",
                hint="A peak that was not observed is 0, not a negative number.",
            )
        if random_intensity <= 0.0:
            raise InvalidInputError(
                f"Line {line}: the random-powder intensity must be strictly positive.",
                field="reflections",
                hint="It divides the measured intensity, so it cannot be zero.",
            )
        plane = CrystalPlane.from_miller_bravais(tuple(indices), phase=phase)
        reflections.append(
            DiffractogramReflection(
                plane=plane, intensity=intensity, random_intensity=random_intensity
            )
        )
    if len(reflections) < 2:
        raise InvalidInputError(
            "The diffractogram route needs at least two reflections at different basal tilts.",
            field="reflections",
            hint=(
                "One peak fixes the pole density at one tilt and says nothing about the rest of "
                "the distribution. Include reflections spanning the range: (0002) at 0 degrees "
                "through (10-10) at 90."
            ),
        )
    return reflections


def _parse_tilt_profile(text: str) -> tuple[np.ndarray, np.ndarray]:
    """Parse ``tilt intensity`` rows, insisting on the equal spacing the quadrature assumes."""

    polar: list[float] = []
    intensity: list[float] = []
    for line, tokens in _data_lines(text, field="profile"):
        if len(tokens) != 2:
            raise InvalidInputError(
                f"Line {line} has {len(tokens)} values; a profile point needs 2.",
                field="profile",
                hint="One tilt angle and one density per line: `25  2.799`.",
            )
        angle = _number(tokens[0], line=line, field="profile", what="a tilt angle")
        if not 0.0 <= angle <= 90.0:
            raise InvalidInputError(
                f"Line {line}: a tilt from the reference direction lies in [0, 90]; got {angle}.",
                field="profile",
            )
        value = _number(tokens[1], line=line, field="profile", what="a pole density")
        if value < 0.0:
            raise InvalidInputError(
                f"Line {line}: a pole density cannot be negative.", field="profile"
            )
        polar.append(angle)
        intensity.append(value)
    if len(polar) < 3:
        raise InvalidInputError(
            "A tilt profile needs at least three points to integrate.",
            field="profile",
            hint="Kearns used nine: the midpoints of 10 degree bins, 5 through 85.",
        )
    angles = np.asarray(polar, dtype=float)
    order = np.argsort(angles)
    angles = angles[order]
    values = np.asarray(intensity, dtype=float)[order]
    steps = np.diff(angles)
    if not np.allclose(steps, steps[0], atol=1e-6):
        raise InvalidInputError(
            "The tilt nodes must be equally spaced; the common bin width is what cancels "
            "out of Kearns' quadrature.",
            field="profile",
            hint=(
                "Use bin midpoints at a constant spacing — 5, 15, 25 ... 85 for 10 degree bins. "
                "Interpolate an unevenly sampled curve onto such a grid first."
            ),
        )
    return angles, values


def _triad_rows(report: Any) -> tuple[tuple[Column, ...], list[dict[str, Any]]]:
    """The per-direction table every route returns, in one shape."""

    columns: tuple[Column, ...] = (
        Column("direction", "Direction", help_text="The specimen direction f is resolved along."),
        Column(
            "f",
            "f",
            numeric=True,
            digits=4,
            help_text="The Kearns parameter: the effective fraction of basal poles along it.",
        ),
        Column(
            "vs_random",
            "f / (1/3)",
            numeric=True,
            digits=3,
            help_text="Against the untextured value of 1/3. Above 1 means poles concentrate here.",
        ),
        Column(
            "mean_angle_deg",
            "Equivalent tilt",
            units="°",
            numeric=True,
            digits=2,
            help_text=(
                "arccos(sqrt(f)): the single basal-pole tilt that would give this f. A summary "
                "of the number, not a measured angle."
            ),
        ),
    )
    rows = [
        {
            "direction": label,
            "f": float(value),
            "vs_random": float(value) / _ISOTROPIC,
            "mean_angle_deg": math.degrees(math.acos(min(1.0, math.sqrt(max(float(value), 0.0))))),
        }
        for label, value in zip(report.direction_labels, report.values, strict=True)
    ]
    return columns, rows


def _report_payload(report: Any, *, spec: PhaseSpec) -> dict[str, Any]:
    """The wire form of a `KearnsReport`, plus what the panel draws.

    Built on the report's own ``to_json`` rather than beside it, so the figure
    and the export cannot describe different numbers. The report's own keys are
    left exactly as it wrote them — in particular ``phase`` stays the plain name
    the JSON contract documents, and the application's fuller specification is
    added beside it as ``phase_spec`` rather than shadowing it.
    """

    payload: dict[str, Any] = dict(report.to_json())
    payload["phase_spec"] = spec.to_json()
    payload["triad_sum"] = report.triad_sum
    payload["is_orthonormal_triad"] = bool(report.is_orthonormal_triad)
    tensor = report.orientation_tensor
    payload["orientation_tensor"] = (
        None if tensor is None else [[float(value) for value in row] for row in np.asarray(tensor)]
    )
    principal = report.principal_values
    payload["principal_values"] = (
        None if principal is None else [float(value) for value in np.asarray(principal)]
    )
    payload["describe"] = report.describe()
    return payload


def _triad_sentence(report: Any) -> str:
    """The closure check, stated the way it should be read."""

    total = report.triad_sum
    if total is None:
        return (
            "The directions are not an orthonormal triad, so the sum rule does not apply and no "
            "closure check is available."
        )
    departure = abs(total - 1.0)
    if departure <= 5e-4:
        return (
            f"The triad sums to {total:.4f}. It is identically 1 for any texture, so this closes "
            "and the result carries no detectable systematic error of that kind."
        )
    return (
        f"The triad sums to {total:.4f}, which departs from 1 by {departure:.4f}. That departure "
        "measures the systematic error of the measurement — an unmeasured tilt range, a wrong "
        "random standard, an unbalanced background — and nothing about the material."
    )


# ---------------------------------------------------------------------------
# Route 1: discrete orientations
# ---------------------------------------------------------------------------


def _model_orientations(
    *, phase: Any, axis_key: str, spread_deg: float, count: int, seed: int
) -> Any:
    """A basal fibre texture: c axes clustered about one specimen axis.

    The tilt angles are drawn from a density proportional to
    ``exp(-phi^2 / 2 sigma^2) sin(phi)``, so ``spread_deg`` is the halfwidth of
    the *pole density on the sphere*. Drawing the tilt from the Gaussian
    directly would give a pole density diverging as ``1 / sin(phi)`` at the
    fibre axis — a singular texture no diffraction route could be fairly judged
    against, and the mistake this sampler exists to avoid.
    """

    from pytex.core.orientation import OrientationSet

    generator = np.random.default_rng(seed)
    axis = np.asarray(_DIRECTION_VECTORS[axis_key], dtype=float)
    grid = np.linspace(0.0, np.pi / 2.0, 4001)
    density = np.exp(-0.5 * (grid / np.deg2rad(spread_deg)) ** 2) * np.sin(grid)
    cumulative = np.cumsum(density)
    cumulative /= cumulative[-1]
    tilt = np.interp(generator.uniform(size=count), cumulative, grid)
    azimuth = generator.uniform(0.0, 2.0 * np.pi, size=count)

    helper = np.array([1.0, 0.0, 0.0]) if abs(axis[0]) < 0.9 else np.array([0.0, 1.0, 0.0])
    first = np.cross(helper, axis)
    first /= np.linalg.norm(first)
    second = np.cross(axis, first)
    c_axes = np.cos(tilt)[:, None] * axis + np.sin(tilt)[:, None] * (
        np.cos(azimuth)[:, None] * first + np.sin(azimuth)[:, None] * second
    )
    # The remaining freedom, rotation about c, is randomized: that is what makes
    # this a basal *fibre* rather than a single component.
    spin = generator.uniform(0.0, 2.0 * np.pi, size=count)
    in_plane = np.tile(np.array([1.0, 0.0, 0.0]), (count, 1))
    in_plane[np.abs(c_axes @ np.array([1.0, 0.0, 0.0])) > 0.9] = np.array([0.0, 1.0, 0.0])
    x_axis = np.cross(in_plane, c_axes)
    x_axis /= np.linalg.norm(x_axis, axis=1, keepdims=True)
    y_axis = np.cross(c_axes, x_axis)
    rotated_x = x_axis * np.cos(spin)[:, None] + y_axis * np.sin(spin)[:, None]
    rotated_y = np.cross(c_axes, rotated_x)
    matrices = np.stack([rotated_x, rotated_y, c_axes], axis=2)
    return OrientationSet.from_matrices(
        matrices,
        crystal_frame=phase.crystal_frame,
        specimen_frame=_specimen_frame(),
        phase=phase,
        symmetry=phase.symmetry,
    )


def _parse_euler_angles(text: str, *, phase: Any) -> Any:
    """Parse pasted Bunge Euler triples into an `OrientationSet`."""

    from pytex.core.orientation import OrientationSet

    angles: list[list[float]] = []
    for line, tokens in _data_lines(text, field="euler_angles"):
        if len(tokens) != 3:
            raise InvalidInputError(
                f"Line {line} has {len(tokens)} values; a Bunge orientation needs 3.",
                field="euler_angles",
                hint="phi1, Phi, phi2 in degrees, one orientation per line: `35 20 45`.",
            )
        angles.append(
            [_number(token, line=line, field="euler_angles", what="an angle") for token in tokens]
        )
    return OrientationSet.from_euler_angles(
        np.asarray(angles, dtype=float),
        specimen_frame=_specimen_frame(),
        crystal_frame=phase.crystal_frame,
        symmetry=phase.symmetry,
        phase=phase,
    )


@REGISTRY.operation(
    "kearns.from_orientations",
    title="Kearns f from orientations",
    summary="The exact route: resolve basal poles of an orientation set onto the specimen axes.",
    help_text=(
        "Computes the Kearns parameter directly from discrete orientations — EBSD data, a "
        "simulation, or the model fibre texture this operation can build for you. It is the "
        "**exact** route: no binning, no interpolation, no tilt truncation, and no "
        "normalisation assumption. The definition `f = <cos^2 phi>` is evaluated as written.\n\n"
        "**Use it as the reference.** Mani Krishna *et al.* (2011) found this the most "
        "consistent route for recrystallised microstructures, and it is the ground truth "
        "against which the diffractogram and tilt-profile routes are judged. Run the model "
        "fibre here, then run the other two operations on their defaults: all three describe "
        "the same synthetic specimen and must agree.\n\n"
        "**The model texture is a basal fibre.** The c axes cluster about one specimen axis "
        "with a stated spread — the idealisation of a rolled or drawn zirconium product. The "
        "spread is the halfwidth of the pole density *on the sphere*, so 0 degrees would be a "
        "single crystal and widening it weakens the texture towards random without reaching "
        "it: at the 90 degree maximum f is about 0.37, not 1/3, because a Gaussian truncated "
        "to the quadrant still leans towards the axis. A random texture is not a wide fibre.\n\n"
        "**Paste your own orientations to override the model.** Bunge (phi1, Phi, phi2) "
        "degrees, one per line. That is the route for EBSD-derived data.\n\n"
        "**Read the triad sum.** f_RD + f_TD + f_ND = 1 exactly, for any texture. This route "
        "closes it by construction, which is precisely why it is the reference."
    ),
    parameters=(
        phase_parameter(
            label="Phase",
            help_text=(
                "The hexagonal phase whose basal pole is resolved. The Kearns parameter is "
                "defined on (0002), so a cubic phase is refused rather than silently answered."
            ),
            builtin="zr_hcp",
        ),
        ChoiceParameter(
            name="fibre_axis",
            label="Model fibre axis",
            help_text=(
                "Which specimen axis the model's basal poles cluster about. Ignored when you "
                "paste your own orientations."
            ),
            options=_DIRECTION_OPTIONS,
            default="ND",
        ),
        NumberParameter(
            name="spread_deg",
            label="Model fibre spread",
            help_text=(
                "Halfwidth of the basal-pole density about the fibre axis. Small is a sharp "
                "texture with f near 1 along the axis; large weakens it towards random without "
                "reaching it — at the 90 degree maximum f is about 0.37, not 1/3."
            ),
            units="°",
            default=30.0,
            minimum=1.0,
            maximum=90.0,
        ),
        TextParameter(
            name="euler_angles",
            label="Or paste orientations",
            help_text=(
                "Bunge Euler angles in degrees — phi1, Phi, phi2 — one orientation per line. "
                "When given, these replace the model texture entirely. Blank lines and text "
                "after `#` are ignored."
            ),
            required=False,
            multiline=True,
            placeholder="35 20 45\n120 18 30",
        ),
        BooleanParameter(
            name="include_symmetry_family",
            label="Average over the {0002} family",
            help_text=(
                "Average the pole's whole symmetry orbit, which is what a diffraction "
                "measurement of a family records. For (0002) in 6/mmm the orbit is the basal "
                "pole and its opposite, and since f depends on c c^T it makes no difference — "
                "the switch matters only for non-basal poles."
            ),
            default=True,
        ),
        NumberParameter(
            name="count",
            label="Model orientations",
            help_text=(
                "How many orientations the model texture holds. More is a smoother estimate; "
                "the sampling error of f falls as one over its square root."
            ),
            default=20000.0,
            minimum=100.0,
            maximum=200000.0,
            advanced=True,
        ),
        NumberParameter(
            name="seed",
            label="Random seed",
            help_text="Fixes the model texture, so the same inputs give the same figure.",
            default=61.0,
            minimum=0.0,
            maximum=1e9,
            advanced=True,
        ),
    ),
    returns=(
        "One row per specimen direction with f, its ratio to the random value, and the "
        "equivalent tilt; the orientation tensor, its principal values, and the triad sum "
        "under `data`."
    ),
    panel="kearns",
    citations=(_CITATION_KEARNS, _CITATION_MANI, _CITATION_HOLT),
    tags=("kearns", "texture", "basal", "zirconium", "EBSD", "orientations", "f factor"),
)
def _from_orientations(request: dict[str, Any]) -> dict[str, Any]:
    from pytex.texture.kearns import kearns_from_orientations

    spec, phase = phase_from_request(request["phase"])
    pole = _basal_pole(phase)
    pasted = str(request["euler_angles"] or "").strip()
    if pasted:
        orientations = _parse_euler_angles(pasted, phase=phase)
        source = f"{len(orientations)} pasted orientations"
        model_inputs: dict[str, Any] = {"source": "pasted"}
    else:
        axis_key = str(request["fibre_axis"])
        spread = float(request["spread_deg"])
        count = int(request["count"])
        seed = int(request["seed"])
        orientations = _model_orientations(
            phase=phase, axis_key=axis_key, spread_deg=spread, count=count, seed=seed
        )
        source = f"a model basal fibre {spread:g}° about {axis_key}, {count} orientations"
        model_inputs = {
            "source": "model",
            "fibre_axis": axis_key,
            "spread_deg": spread,
            "count": count,
            "seed": seed,
        }

    report = kearns_from_orientations(
        orientations,
        pole=pole,
        include_symmetry_family=bool(request["include_symmetry_family"]),
    )
    columns, rows = _triad_rows(report)
    strongest = max(rows, key=lambda row: row["f"])
    result = AppResult(
        title=f"Kearns parameters of {spec.name} from {source}",
        summary=(
            f"f_RD = {rows[0]['f']:.4f}, f_TD = {rows[1]['f']:.4f}, f_ND = {rows[2]['f']:.4f}, "
            f"resolved from the (0002) pole of {len(orientations)} orientations. The largest is "
            f"f_{strongest['direction']} = {strongest['f']:.4f}, "
            f"{strongest['vs_random']:.2f} times the untextured value of 1/3. "
            + _triad_sentence(report)
            + " This route evaluates the definition directly, so it carries no binning, "
            "truncation, or normalisation error for the other routes to be compared against."
        ),
        table=ResultTable(
            columns=columns,
            rows=tuple(rows),
            caption="The Kearns parameter along each specimen direction.",
        ),
        data=_report_payload(report, spec=spec),
        inputs=dict(
            model_inputs,
            phase=spec.to_json(),
            include_symmetry_family=bool(request["include_symmetry_family"]),
        ),
        notes=(
            "f is a mean of cos^2, so it lies in [0, 1] and equals 1/3 for a random aggregate. "
            "It is not a volume fraction of any set of grains.",
            "The parameter summarises the texture only for properties of the Kearns form "
            "P = P_par cos^2 phi + P_perp sin^2 phi — second-rank properties such as thermal "
            "expansion and irradiation growth. It says nothing about properties of other "
            "tensor rank.",
        ),
        citations=(_CITATION_KEARNS, _CITATION_MANI, _CITATION_HOLT),
    )
    return result.to_json()


# ---------------------------------------------------------------------------
# Route 2: the theta-2theta diffractogram
# ---------------------------------------------------------------------------


@REGISTRY.operation(
    "kearns.from_diffractogram",
    title="Kearns f from a 2theta scan",
    summary="Kearns' original route: peak intensities of a symmetric scan against a random powder.",
    help_text=(
        "Kearns' own 1965 method, and still the only one that needs no texture goniometer. "
        "Measure the integrated intensity of every `(hkil)` peak on a flat section, compare "
        "each with a random powder, and read the ratio as the basal-pole density at that "
        "reflection's known tilt to `[0001]`. The intensities are an inverse pole figure of the "
        "section normal.\n\n"
        "**Give the random-powder intensity.** Raw peak heights are not pole densities: "
        "reflections differ by orders of magnitude in structure factor and multiplicity. Measure "
        "a powder standard under identical conditions, or calculate the intensities from the "
        "structure. Only ratios enter f, so arbitrary units are fine — but a missing standard "
        "is not a small error, it is the whole normalisation.\n\n"
        "**Span the tilt range.** The `sin phi` factor in Kearns' integral makes the high-tilt "
        "reflections matter far more than their intensity suggests. `(10-10)` at 90 degrees and "
        "`(10-13)` at 31.5 degrees carry weight that `(0002)` does not; omitting the high-tilt "
        "peaks biases f upward.\n\n"
        "**One section gives one number.** This route measures f along the section normal only. "
        "The full triad needs all three principal sections, which for thin product forms means "
        "stacking slices — and the three will not sum to 1 without care, which is exactly the "
        "diagnostic to watch.\n\n"
        "**The defaults are synthetic and the answer is known.** They are the peaks a basal "
        "fibre of 30 degree spread about ND would give, whose true f_ND is 0.642. Press the "
        "button and watch the route recover it."
    ),
    parameters=(
        phase_parameter(
            label="Phase",
            help_text="The hexagonal phase the reflections belong to.",
            builtin="zr_hcp",
        ),
        TextParameter(
            name="reflections",
            label="Measured reflections",
            help_text=(
                "One peak per line: the four Miller-Bravais indices, the measured integrated "
                "intensity, then the random-powder intensity — `1 0 -1 3  2.292  1.0`. The "
                "random intensity may be omitted, in which case it is taken as 1, which is only "
                "right if the intensities are already in times-random units. Text after `#` is "
                "a comment."
            ),
            multiline=True,
            default=_DEFAULT_REFLECTIONS,
        ),
        ChoiceParameter(
            name="normalization",
            label="Normalisation",
            help_text=(
                "How measured intensities become pole densities. Both give the same f; they "
                "differ in what they assume you measured."
            ),
            options=(
                (
                    "random_standard",
                    "Against a random standard",
                    "Divide each peak by its random-powder intensity — Kearns' own choice.",
                ),
                (
                    "harris",
                    "Harris texture coefficients",
                    "Normalise so the mean coefficient is 1, the crystallographic-texture-"
                    "coefficient convention.",
                ),
            ),
            default="random_standard",
        ),
        NumberParameter(
            name="bin_width_deg",
            label="Tilt bin width",
            help_text=(
                "Width of the tilt bins the reflections are interpolated onto before the "
                "quadrature. Kearns used 10 degrees, and finer bins do not add information the "
                "reflection list does not already carry."
            ),
            units="°",
            default=10.0,
            minimum=2.0,
            maximum=30.0,
        ),
        ChoiceParameter(
            name="direction",
            label="Section normal",
            help_text=(
                "Which specimen direction this section's normal represents — the direction the "
                "resulting f refers to."
            ),
            options=_DIRECTION_OPTIONS,
            default="ND",
        ),
    ),
    returns=(
        "One row per reflection with its basal tilt and normalised pole density, plus f along "
        "the section normal; the interpolated tilt profile and the Harris coefficients under "
        "`data`."
    ),
    panel="kearns",
    citations=(_CITATION_KEARNS, _CITATION_MANI),
    tags=("kearns", "XRD", "2theta", "diffractogram", "Harris", "inverse pole figure", "texture"),
)
def _from_diffractogram(request: dict[str, Any]) -> dict[str, Any]:
    from pytex.texture.kearns import (
        basal_tilt_profile,
        harris_texture_coefficients,
        kearns_from_diffractogram,
    )

    spec, phase = phase_from_request(request["phase"])
    _basal_pole(phase)
    reflections = _parse_reflections(str(request["reflections"]), phase=phase)
    normalization = str(request["normalization"])
    bin_width = float(request["bin_width_deg"])
    direction_label = str(request["direction"])

    report = kearns_from_diffractogram(
        reflections,
        specimen_frame=_specimen_frame(),
        normalization=normalization,
        bin_width_deg=bin_width,
        direction=_DIRECTION_VECTORS[direction_label],
        direction_label=direction_label,
    )
    polar_deg, profile, profile_notes = basal_tilt_profile(
        reflections, normalization=normalization, bin_width_deg=bin_width
    )
    harris = harris_texture_coefficients([item.intensity for item in reflections])

    columns: tuple[Column, ...] = (
        Column("plane", "Reflection", help_text="The reflecting plane, in Miller-Bravais form."),
        Column(
            "basal_tilt_deg",
            "Tilt to [0001]",
            units="°",
            numeric=True,
            digits=2,
            help_text="Angle between this plane's normal and the c axis, from the phase metric.",
        ),
        Column("intensity", "Measured I", numeric=True, digits=4),
        Column("random_intensity", "Random I", numeric=True, digits=4),
        Column(
            "density",
            "Pole density",
            numeric=True,
            digits=4,
            help_text="Measured over random: the basal-pole density at this reflection's tilt.",
        ),
        Column(
            "harris",
            "Harris coefficient",
            numeric=True,
            digits=4,
            help_text="The same intensities normalised so the mean coefficient is 1.",
        ),
    )
    rows: list[dict[str, Any]] = [
        {
            "plane": _reflection_label(reflection),
            "basal_tilt_deg": float(reflection.basal_tilt_deg),
            "intensity": float(reflection.intensity),
            "random_intensity": float(reflection.random_intensity or 1.0),
            "density": float(reflection.intensity) / float(reflection.random_intensity or 1.0),
            "harris": float(harris[index]),
        }
        for index, reflection in enumerate(reflections)
    ]
    rows.sort(key=lambda row: row["basal_tilt_deg"])

    value = report.value(direction_label)
    tilt_span = rows[-1]["basal_tilt_deg"] - rows[0]["basal_tilt_deg"]
    payload = _report_payload(report, spec=spec)
    payload["profile"] = {
        "polar_deg": [float(item) for item in np.asarray(polar_deg, dtype=float)],
        "intensity": [float(item) for item in np.asarray(profile, dtype=float)],
        "notes": list(profile_notes),
    }
    payload["reflections"] = rows

    result = AppResult(
        title=f"Kearns f_{direction_label} of {spec.name} from a theta-2theta scan",
        summary=(
            f"f_{direction_label} = {value:.4f} from {len(reflections)} reflections spanning "
            f"{tilt_span:.1f}° of basal tilt, {value / _ISOTROPIC:.2f} times the untextured "
            f"value of 1/3. The intensities were normalised "
            + (
                "against the supplied random-powder standard"
                if normalization == "random_standard"
                else "to Harris texture coefficients"
            )
            + f", interpolated onto {len(np.asarray(polar_deg))} tilt bins of {bin_width:g}°, and "
            "integrated by Kearns' Eq. (5). This route measures one direction per section, so "
            "the triad needs all three principal sections and no closure check is available "
            "from a single run."
        ),
        table=ResultTable(
            columns=columns,
            rows=tuple(rows),
            caption="Each reflection at its basal tilt, with the pole density it implies.",
        ),
        data=payload,
        inputs={
            "phase": spec.to_json(),
            "normalization": normalization,
            "bin_width_deg": bin_width,
            "direction": direction_label,
            "reflection_count": len(reflections),
        },
        notes=(
            *report.notes,
            *profile_notes,
            "The tilt profile is the most informative plot in the method: it is the "
            "azimuthally averaged basal-pole density, and f is its cos^2-weighted mean. A "
            "profile with a gap in the middle of the tilt range means the integral is "
            "interpolating over a range nothing measured.",
        ),
        citations=(_CITATION_KEARNS, _CITATION_MANI),
    )
    return result.to_json()


def _reflection_label(reflection: Any) -> str:
    """The four-index label of a reflection's plane, as the tables write it.

    Formatted through `pytex.core.notation` rather than inline, and in the
    Miller-Bravais form because that is what the zirconium literature the
    intensities will be compared against uses.
    """

    from pytex.core.hexagonal import plane_hkl_to_hkil
    from pytex.core.notation import format_miller_indices

    indices = tuple(int(value) for value in reflection.plane.miller.indices)
    indices = tuple(int(value) for value in plane_hkl_to_hkil(indices))
    return format_miller_indices(indices, family="plane", style="plain", scope="specific")


# ---------------------------------------------------------------------------
# Route 3: the basal-pole tilt profile
# ---------------------------------------------------------------------------


@REGISTRY.operation(
    "kearns.from_tilt_profile",
    title="Kearns f from a tilt profile",
    summary="Integrate an azimuthally averaged basal-pole density over tilt — Kearns' Eq. (5).",
    help_text=(
        "The innermost calculation of the whole method, exposed on its own. Kearns showed that "
        "f needs only the pole density averaged over the full 360 degrees of azimuth, `I(phi)`, "
        "as a function of tilt `phi` from the reference direction. The azimuthal detail of a "
        "pole figure is irrelevant to a second-rank property, so a whole figure collapses to "
        "one curve with no loss for this purpose.\n\n"
        "**Use it** when the tilt profile is what you have: a pole-figure ring average, a "
        "published `I(phi)` curve, or the profile the diffractogram route prints. It is also "
        "the way to reproduce a literature calculation, since it is exactly the tabulated "
        "procedure of Kearns' Table 3.\n\n"
        "**Why high tilt matters more than it looks.** The `sin phi` factor converts pole "
        "density to volume fraction: the ring of orientations at tilt `phi` has circumference "
        "proportional to `sin phi`. So the profile at 75 degrees carries real weight even where "
        "the density is small, and the volume fraction vanishes at `phi = 0` however intense "
        "the pole is there.\n\n"
        "**The nodes must be equally spaced.** Samples are treated as bin representatives, as in "
        "Kearns' Table 3, so the common bin width cancels from the quotient. Bin midpoints — 5, "
        "15, ... 85 for 10 degree bins — are the classical choice and avoid the endpoints, where "
        "the integrand vanishes or the measurement is worst.\n\n"
        "**The scale does not matter.** f is a quotient of two integrals of `I`, so times-random, "
        "counts, or anything proportional to density all give the same answer."
    ),
    parameters=(
        phase_parameter(
            label="Phase",
            help_text="The hexagonal phase whose basal pole the profile describes.",
            builtin="zr_hcp",
        ),
        TextParameter(
            name="profile",
            label="Tilt profile",
            help_text=(
                "One point per line: the tilt from the reference direction in degrees, then the "
                "azimuthally averaged pole density in any units proportional to density — "
                "`25  2.799`. The nodes must be equally spaced. Text after `#` is a comment."
            ),
            multiline=True,
            default=_DEFAULT_TILT_PROFILE,
        ),
        ChoiceParameter(
            name="direction",
            label="Reference direction",
            help_text="The specimen direction the tilt is measured from, and that f refers to.",
            options=_DIRECTION_OPTIONS,
            default="ND",
        ),
    ),
    returns=(
        "One row per profile node with its volume-fraction weight and cos^2 contribution, plus "
        "f along the reference direction."
    ),
    panel="kearns",
    citations=(_CITATION_KEARNS, _CITATION_BARON),
    tags=("kearns", "tilt profile", "quadrature", "basal", "texture", "zirconium"),
)
def _from_tilt_profile(request: dict[str, Any]) -> dict[str, Any]:
    from pytex.texture.kearns import kearns_from_tilt_profile

    spec, phase = phase_from_request(request["phase"])
    pole = _basal_pole(phase)
    polar_deg, intensity = _parse_tilt_profile(str(request["profile"]))
    direction_label = str(request["direction"])

    report = kearns_from_tilt_profile(
        polar_deg,
        intensity,
        pole=pole,
        specimen_frame=_specimen_frame(),
        direction=_DIRECTION_VECTORS[direction_label],
        direction_label=direction_label,
    )

    # The same quadrature the function integrates, reported per node so the
    # user can see where f came from rather than only what it was.
    radians = np.deg2rad(polar_deg)
    volume_weight = intensity * np.sin(radians)
    total = float(volume_weight.sum())
    fractions = volume_weight / total if total > 0.0 else np.zeros_like(volume_weight)

    columns: tuple[Column, ...] = (
        Column("polar_deg", "Tilt", units="°", numeric=True, digits=1),
        Column("intensity", "Pole density", numeric=True, digits=4),
        Column(
            "volume_fraction",
            "Volume fraction",
            numeric=True,
            digits=5,
            help_text="I sin(phi), normalised: the fraction of crystals at this tilt.",
        ),
        Column(
            "cos2",
            "cos²φ",
            numeric=True,
            digits=5,
            help_text="What this tilt contributes per unit volume fraction.",
        ),
        Column(
            "contribution",
            "Contribution to f",
            numeric=True,
            digits=5,
            help_text="Volume fraction times cos²φ. These sum to f.",
        ),
    )
    cos2 = np.cos(radians) ** 2
    rows: list[dict[str, Any]] = [
        {
            "polar_deg": float(polar_deg[index]),
            "intensity": float(intensity[index]),
            "volume_fraction": float(fractions[index]),
            "cos2": float(cos2[index]),
            "contribution": float(fractions[index] * cos2[index]),
        }
        for index in range(polar_deg.size)
    ]
    dominant = max(rows, key=lambda row: row["contribution"])
    value = report.value(direction_label)
    payload = _report_payload(report, spec=spec)
    payload["profile"] = {
        "polar_deg": [float(item) for item in polar_deg],
        "intensity": [float(item) for item in intensity],
        "notes": [],
    }
    payload["quadrature"] = rows

    result = AppResult(
        title=f"Kearns f_{direction_label} of {spec.name} from a tilt profile",
        summary=(
            f"f_{direction_label} = {value:.4f} from {polar_deg.size} nodes spanning "
            f"{polar_deg[0]:.0f}° to {polar_deg[-1]:.0f}° in steps of "
            f"{polar_deg[1] - polar_deg[0]:.0f}°, {value / _ISOTROPIC:.2f} times the untextured "
            f"value of 1/3. The largest single contribution comes from the "
            f"{dominant['polar_deg']:.0f}° node, which holds "
            f"{dominant['volume_fraction'] * 100:.1f}% of the volume at cos²φ = "
            f"{dominant['cos2']:.3f}. The contributions in the table sum to f, so the row that "
            "dominates it is visible rather than inferred."
        ),
        table=ResultTable(
            columns=columns,
            rows=tuple(rows),
            caption="Kearns' quadrature, node by node.",
        ),
        data=payload,
        inputs={
            "phase": spec.to_json(),
            "direction": direction_label,
            "node_count": int(polar_deg.size),
            "step_deg": float(polar_deg[1] - polar_deg[0]),
        },
        notes=(
            *report.notes,
            "The volume fraction, not the pole density, is what f averages. A profile that "
            "peaks at zero tilt still contributes nothing there, because the ring of "
            "orientations at zero tilt has no circumference.",
        ),
        citations=(_CITATION_KEARNS, _CITATION_BARON),
    )
    return result.to_json()


REGISTRY.add_examples(
    (
        ExampleScenario(
            id="kearns.example.model_fibre",
            title="A basal fibre, and its triad",
            panel="kearns",
            summary="The exact route on a model basal fibre 30° about ND.",
            teaches=(
                "Three numbers, and they sum to exactly 1 — not approximately, and not because "
                "this texture is special. f is the diagonal of a second-moment tensor of unit "
                "vectors, so its trace is 1 for every texture there is. That makes the sum the "
                "single most useful check on any Kearns measurement: it tests the measurement, "
                "never the material. Note also that f_RD and f_TD come out equal, which is what "
                "a *fibre* means — and that neither is zero, because a 30° spread still puts "
                "plenty of basal poles away from ND."
            ),
            operation="kearns.from_orientations",
            request={
                "phase": {"builtin": "zr_hcp"},
                "fibre_axis": "ND",
                "spread_deg": 30.0,
            },
        ),
        ExampleScenario(
            id="kearns.example.diffractogram",
            title="The same specimen, measured by X-ray",
            panel="kearns",
            summary="Kearns' 1965 route on the peaks that fibre texture would give.",
            teaches=(
                "Run this straight after the model fibre. The reflection intensities here were "
                "generated from *that* texture, so the true answer is the f_ND the previous "
                "example printed — and this route, which sees only thirteen peak heights and "
                "knows nothing about orientations, recovers it. That is the claim Kearns made "
                "in 1965 and it is worth watching happen. Look at the tilt column: (0002) sits "
                "at 0° and (10-10) at 90°, and it is the spread across that range, not the "
                "height of any one peak, that determines f."
            ),
            operation="kearns.from_diffractogram",
            request={"phase": {"builtin": "zr_hcp"}, "direction": "ND"},
        ),
        ExampleScenario(
            id="kearns.example.tilt_profile",
            title="Kearns' own quadrature, node by node",
            panel="kearns",
            summary="The nine-node integration of Kearns' Table 3, on the same specimen again.",
            teaches=(
                "The third route on the same synthetic specimen, and the same answer a third "
                "time. What this one adds is the arithmetic: the table shows the volume "
                "fraction at each tilt and what it contributes, and those contributions sum to "
                "f. Notice that the 5° node has the highest pole density of all and one of the "
                "smallest volume fractions — the ring of crystals at 5° tilt is tiny however "
                "intense it is. That sin(phi) factor is the part of the method most often got "
                "wrong."
            ),
            operation="kearns.from_tilt_profile",
            request={"phase": {"builtin": "zr_hcp"}, "direction": "ND"},
        ),
    )
)
