"""Solving the holder angles that bring a target zone axis onto the beam.

This is the entry point of `pytex.tem`. Given a reconstructed crystal-to-holder
orientation and a requested zone axis, it enumerates every crystallographically
acceptable version of the target, solves the stage angles for each in closed
form, refines them through the calibrated stage model when the stage is not
ideal, validates every candidate by forward simulation, ranks the survivors, and
plans a path to each.

The closed form
---------------
With ``w = U t`` the target direction expressed in holder coordinates, matching
against the beam-direction formula gives, in two lines,

    beta  = atan2(-w1, w3)
    alpha = atan2(w2, hypot(w1, w3))

which places ``w`` along the beam. Four branches satisfy the alignment condition;
two require ``|beta| > 90 deg`` and one requires roughly ``180 deg`` of alpha, so
on a real holder exactly one is relevant. **The combinatorial richness of the
answer therefore comes from symmetry and ambiguity, not from the trigonometry** —
which is why most of this module is about enumerating candidates and telling
choices apart from hypotheses, rather than about solving equations.

Choices versus hypotheses
-------------------------
Symmetry-equivalent targets and ambiguity families are generated by similar group
operations and must never be presented alike. A symmetry equivalent is a *choice*
the operator may take at will: every equivalent gives the same diffraction
pattern, so the cheapest reachable one is simply better. An ambiguity family is a
competing *hypothesis* about reality, of which only one is true; acting on the
wrong one puts the specimen somewhere else. Every solution records which orbit
member it lands on and which family it belongs to.

Forward validation
------------------
No solution reaches the caller without being re-derived through the calibrated
forward model and checked against the requested tolerance. Solutions that fail
are rejected *before* ranking rather than down-weighted, so a solver bug cannot
present itself as a low-scoring answer.

See ``docs/architecture/tem_tilt_navigation_foundation.md`` sections 6, 7 and 10.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from enum import StrEnum
from functools import lru_cache
from typing import Any

import numpy as np
from numpy.typing import ArrayLike

from pytex.core._arrays import as_float_array, normalize_vector
from pytex.core.lattice import CrystalDirection, Phase, ZoneAxis
from pytex.core.notation import format_direction_indices
from pytex.core.provenance import ProvenanceRecord
from pytex.tem.ambiguity import AmbiguityFamily, AmbiguityReport
from pytex.tem.path import (
    DEFAULT_MARGIN_FLOOR_DEG,
    DEFAULT_PATH_SAMPLES,
    PathStrategy,
    TiltPath,
    plan_path,
    suggest_waypoints,
)
from pytex.tem.reconstruction import CurrentState
from pytex.tem.stage import (
    BEAM_AXIS_LABORATORY,
    GIMBAL_TOLERANCE,
    DoubleTiltStage,
    StageModel,
    StagePosition,
    beam_direction_holder,
)

__all__ = [
    "DEFAULT_RANKING",
    "DEFAULT_TOLERANCE_DEG",
    "LONG_HOP_THRESHOLD_DEG",
    "RankingWeights",
    "Reachability",
    "TiltPlanReport",
    "TiltSolution",
    "plan_tilt_to_zone_axis",
    "solve_tilts_for_direction",
]

#: Default angular tolerance on the forward-validated residual, in degrees.
#:
#: Half a degree is the working figure: comfortably tighter than the width of a
#: zone-axis orientation "well" at typical foil thicknesses, so a solution inside
#: it shows the intended pattern, and comfortably looser than the stage readout
#: precision, so an achievable solution is not rejected for arithmetic reasons.
DEFAULT_TOLERANCE_DEG = 0.5

#: Beyond this hop length, multi-hop routing through intermediate zones is advised.
#:
#: From the residual law, an error ``dphi`` in the diffraction rotation costs
#: about ``dphi sin(theta)``. At 30 degrees a 5 degree calibration error already
#: costs 2.5 degrees, which exceeds the default tolerance five-fold.
LONG_HOP_THRESHOLD_DEG = 30.0


class Reachability(StrEnum):
    """How well a solution answers the request.

    The four verdicts are qualitatively different answers, not gradations of one
    answer, and the API keeps them apart so that a caller cannot mistake a
    nearest approach for a hit.
    """

    #: Forward-validated within tolerance, comfortably inside the envelope.
    EXACT = "exact"
    #: Reachable and within tolerance, but with a residual worth stating.
    WITHIN_TOLERANCE = "within_tolerance"
    #: No orbit member is reachable; this is the closest the holder can come.
    NEAREST_APPROACH = "nearest_approach"
    #: Not reachable, and not close enough for a partial tilt to be useful.
    UNREACHABLE = "unreachable"


@dataclass(frozen=True, slots=True)
class RankingWeights:
    """Relative importance of the criteria used to rank feasible solutions.

    Purpose
    -------
    Makes the ranking policy explicit and overridable instead of burying it in a
    comparison function. The defaults favour a short, safe, well-conditioned move
    over a marginally shorter one that ends near a mechanical stop.

    Attributes
    ----------
    travel : float
        Weight on the specimen rotation angle. The dominant term: a shorter move
        is faster, and is more robust to a stale rotation calibration because the
        residual from such an error scales with the length of the hop.
    largest_axis_move : float
        Weight on ``max(|d_alpha|, |d_beta|)``, which is what limits the move
        when only one axis can be driven at a time.
    limit_penalty : float
        Weight on a soft barrier against the envelope boundary.
    uncertainty : float
        Weight on the propagated one-sigma residual.
    conditioning : float
        Weight on ``1/cos(alpha) - 1``. The stage parameterization is singular at
        the beta-axis pole; within a real envelope the amplification is at most
        about 1.3, so this is a tie-breaker rather than a veto.
    margin_scale_deg : float
        Length scale of the soft barrier.
    """

    travel: float = 1.0
    largest_axis_move: float = 0.3
    limit_penalty: float = 20.0
    uncertainty: float = 4.0
    conditioning: float = 10.0
    margin_scale_deg: float = 5.0

    def cost(
        self,
        *,
        travel_deg: float,
        largest_axis_move_deg: float,
        margin_deg: float,
        uncertainty_deg: float,
        conditioning: float,
    ) -> float:
        """Combine the criteria into a single scalar cost; lower is better."""

        barrier = math.exp(-max(margin_deg, 0.0) / max(self.margin_scale_deg, 1e-9))
        return float(
            self.travel * travel_deg
            + self.largest_axis_move * largest_axis_move_deg
            + self.limit_penalty * barrier
            + self.uncertainty * uncertainty_deg
            + self.conditioning * max(conditioning - 1.0, 0.0)
        )


#: The default ranking policy.
DEFAULT_RANKING = RankingWeights()


def _int_list(values: ArrayLike) -> list[int]:
    """Round an index array to the plain integer list the notation helpers take.

    Crystallographic notation is produced only by `pytex.core.notation`, whose
    helpers take a sequence of integers; this is the single conversion point so
    that no caller is tempted to format indices inline.
    """

    return [round(float(value)) for value in np.asarray(values).ravel()]


def solve_tilts_for_direction(
    direction_holder: ArrayLike,
    *,
    allow_reverse: bool = True,
) -> tuple[tuple[float, float], ...]:
    """Stage angles that bring a holder-frame direction onto the beam.

    Purpose
    -------
    The closed form at the heart of the package. Given a direction already
    expressed in holder coordinates, returns every ``(alpha, beta)`` branch that
    aligns it with the beam axis. This is pure geometry: no envelope, no
    symmetry, no calibration.

    When to use
    -----------
    Directly, when the orientation work has already been done and only the
    trigonometry is wanted — for instance inside a reachability sweep. Most
    callers want :func:`plan_tilt_to_zone_axis` instead, which handles symmetry,
    validation and ranking.

    Parameters
    ----------
    direction_holder : array_like
        A direction in holder coordinates; need not be normalized.
    allow_reverse : bool, default True
        Include the branches that place the direction *anti*-parallel to the
        beam. A kinematic pattern cannot distinguish the two senses, so both are
        usually acceptable.

    Returns
    -------
    tuple of (float, float)
        Stage angles in degrees, principal branch first. Two branches when
        ``allow_reverse`` is false, four when it is true.

    Notes
    -----
    When the direction lies along the beta axis the beta angle is indeterminate
    and the solution degenerates to a one-parameter family; this returns the
    ``beta = 0`` representative with ``alpha = +/-90``, which no real holder
    reaches. The degeneracy is detected rather than producing an arbitrary
    ``atan2(0, 0)``.

    Examples
    --------
    The holder ``z`` axis is already on the beam, so the principal branch is the
    zero position::

        >>> solve_tilts_for_direction([0.0, 0.0, 1.0])[0]
        (0.0, 0.0)
    """

    w = normalize_vector(direction_holder)
    w1, w2, w3 = (float(value) for value in w)
    rho = math.hypot(w1, w3)

    if rho < GIMBAL_TOLERANCE:
        alpha = 90.0 if w2 > 0.0 else -90.0
        branches = [(alpha, 0.0)]
        if allow_reverse:
            branches.append((-alpha, 0.0))
        return tuple(branches)

    beta = math.degrees(math.atan2(-w1, w3))
    beta_opposite = beta + 180.0 if beta <= 0.0 else beta - 180.0
    alpha = math.degrees(math.atan2(w2, rho))
    alpha_opposite = math.degrees(math.atan2(w2, -rho))

    branches = [(alpha, beta), (alpha_opposite, beta_opposite)]
    if allow_reverse:
        branches.append((math.degrees(math.atan2(-w2, -rho)), beta))
        branches.append((math.degrees(math.atan2(-w2, rho)), beta_opposite))
    return tuple((float(a), float(b)) for a, b in branches)


@dataclass(frozen=True, slots=True)
class TiltSolution:
    """One ranked way to reach the requested target, with its evidence.

    Purpose
    -------
    A complete, self-contained answer: where to tilt, which crystallographic
    direction will actually be on the beam when you get there, how far off it
    will be, how confident that is, how to get there, and which orientation
    hypothesis it assumes.

    Attributes
    ----------
    position : StagePosition
        The stage angles to drive to.
    verdict : Reachability
    residual_deg : float
        Forward-validated angle between the achieved direction and the beam.
        Computed by re-deriving the result through the calibrated stage model,
        not by re-reading the solver's own output.
    orbit_member : np.ndarray
        The Cartesian crystal-frame direction actually placed on the beam. When
        this is a symmetry equivalent of the request rather than the request
        itself, the pattern is identical but the in-plane azimuth differs.
    orbit_member_indices : np.ndarray or None
        The same direction as rationalized integer indices, when it rationalizes.
    family : AmbiguityFamily
        The orientation hypothesis this solution assumes.
    is_reversed : bool
        Whether the direction sits antiparallel to the beam. Both senses give the
        same kinematic pattern.
    travel_deg : float
        Angle of the specimen rotation between current and target positions.
    delta_alpha_deg, delta_beta_deg : float
    envelope_margin_deg : float
    conditioning : float
        ``1/cos(alpha)`` at the destination: how much a direction error is
        amplified into a beta error there.
    sigma_alpha_deg, sigma_beta_deg, sigma_residual_deg : float
        Propagated one-sigma uncertainties.
    path : TiltPath or None
    cost : float
        Ranking score; lower is better.
    notes : tuple of str
    """

    position: StagePosition
    verdict: Reachability
    residual_deg: float
    orbit_member: np.ndarray
    orbit_member_indices: np.ndarray | None
    family: AmbiguityFamily
    is_reversed: bool
    travel_deg: float
    delta_alpha_deg: float
    delta_beta_deg: float
    envelope_margin_deg: float
    conditioning: float
    sigma_alpha_deg: float
    sigma_beta_deg: float
    sigma_residual_deg: float
    path: TiltPath | None = None
    cost: float = 0.0
    notes: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        object.__setattr__(
            self, "orbit_member", as_float_array(self.orbit_member, shape=(3,))
        )
        object.__setattr__(self, "notes", tuple(self.notes))

    @property
    def is_requested_direction(self) -> bool:
        """Whether this lands on the requested direction rather than an equivalent."""

        return bool(self.notes and "requested direction" in self.notes[0])

    def describe(self) -> str:
        """Prose an operator can act on, with the conventions made explicit."""

        target_text = (
            format_direction_indices(_int_list(self.orbit_member_indices))
            if self.orbit_member_indices is not None
            else "the requested direction"
        )
        sense = (
            " (antiparallel to the beam; the same kinematic pattern)"
            if self.is_reversed
            else ""
        )
        head = (
            f"Drive to alpha {self.position.alpha_deg:+.2f} deg, beta "
            f"{self.position.beta_deg:+.2f} deg — a change of "
            f"{self.delta_alpha_deg:+.2f} and {self.delta_beta_deg:+.2f} deg — which "
            f"places {target_text}{sense} on the electron beam."
        )
        quality = (
            f" Forward-validated residual {self.residual_deg:.4f} deg "
            f"(+/- {self.sigma_residual_deg:.2f} deg from the propagated input "
            f"uncertainties); verdict {self.verdict.value}."
        )
        mechanics = (
            f" Specimen rotation {self.travel_deg:.1f} deg; envelope clearance at the "
            f"destination {self.envelope_margin_deg:.1f} deg; beta conditioning factor "
            f"{self.conditioning:.2f}."
        )
        uncertainty = (
            f" Stage-angle uncertainty {self.sigma_alpha_deg:.2f} deg in alpha and "
            f"{self.sigma_beta_deg:.2f} deg in beta."
        )
        family = "" if self.family.index == 1 else f" {self.family.describe()}"
        extra = (" " + " ".join(self.notes)) if self.notes else ""
        path = f" {self.path.describe()}" if self.path is not None else ""
        return head + quality + mechanics + uncertainty + family + extra + path

    def to_json_dict(self) -> dict[str, Any]:
        """Serializable payload, kept in lockstep with :meth:`describe`."""

        return {
            "alpha_deg": self.position.alpha_deg,
            "beta_deg": self.position.beta_deg,
            "verdict": self.verdict.value,
            "residual_deg": self.residual_deg,
            "orbit_member": self.orbit_member.tolist(),
            "orbit_member_indices": (
                None
                if self.orbit_member_indices is None
                else [int(value) for value in self.orbit_member_indices]
            ),
            "family_index": self.family.index,
            "is_reversed": self.is_reversed,
            "travel_deg": self.travel_deg,
            "delta_alpha_deg": self.delta_alpha_deg,
            "delta_beta_deg": self.delta_beta_deg,
            "envelope_margin_deg": self.envelope_margin_deg,
            "conditioning": self.conditioning,
            "sigma_alpha_deg": self.sigma_alpha_deg,
            "sigma_beta_deg": self.sigma_beta_deg,
            "sigma_residual_deg": self.sigma_residual_deg,
            "cost": self.cost,
            "path": None if self.path is None else self.path.to_json_dict(),
            "notes": list(self.notes),
        }


@dataclass(frozen=True, slots=True)
class TiltPlanReport:
    """The full answer: ranked solutions, what is undetermined, and what to do.

    Purpose
    -------
    The object returned to the user. It exists to make three things impossible:
    presenting one member of an ambiguity class as *the* answer, presenting a
    nearest approach as a hit, and presenting a solution that was never
    forward-validated.

    Attributes
    ----------
    solutions : tuple of TiltSolution
        Ranked, best first. Empty when nothing is reachable, in which case
        :attr:`nearest_approach` carries the closest the holder can come.
    current : CurrentState
    target : ZoneAxis
    ambiguity : AmbiguityReport
    orbit_size : int
        How many distinct directions the symmetry orbit of the target contains,
        counting both senses.
    reachable_orbit_size : int
    nearest_approach : TiltSolution or None
        Populated when nothing was reachable exactly.
    tolerance_deg : float
    waypoints : tuple of CrystalDirection
        Suggested intermediate zones for a long hop.
    notes : tuple of str
    provenance : ProvenanceRecord or None
    """

    solutions: tuple[TiltSolution, ...]
    current: CurrentState
    target: ZoneAxis
    ambiguity: AmbiguityReport
    orbit_size: int
    reachable_orbit_size: int
    nearest_approach: TiltSolution | None = None
    tolerance_deg: float = DEFAULT_TOLERANCE_DEG
    waypoints: tuple[CrystalDirection, ...] = ()
    notes: tuple[str, ...] = ()
    provenance: ProvenanceRecord | None = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "solutions", tuple(self.solutions))
        object.__setattr__(self, "waypoints", tuple(self.waypoints))
        object.__setattr__(self, "notes", tuple(self.notes))

    def __len__(self) -> int:
        return len(self.solutions)

    @property
    def is_reachable(self) -> bool:
        """Whether at least one solution passed forward validation."""

        return bool(self.solutions)

    def best(self) -> TiltSolution:
        """The highest-ranked solution, or raise with a diagnosis."""

        if not self.solutions:
            nearest = ""
            if self.nearest_approach is not None:
                nearest = (
                    f" The closest the holder can come is "
                    f"{self.nearest_approach.position}, leaving "
                    f"{self.nearest_approach.residual_deg:.1f} deg between the target "
                    "and the beam."
                )
            raise ValueError(
                f"No reachable solution was found for "
                f"{format_direction_indices(_int_list(self.target.indices))} within "
                f"{self.tolerance_deg:g} deg. None of the {self.orbit_size} "
                f"symmetry-equivalent directions falls inside the holder envelope."
                + nearest
            )
        return self.solutions[0]

    def describe(self) -> str:
        """The whole answer as prose, conventions stated, ambiguity included."""

        target_text = format_direction_indices(_int_list(self.target.indices))
        head = (
            f"Target {target_text} in {self.current.phase.name}: the symmetry orbit "
            f"contains {self.orbit_size} distinct directions (counting both senses), of "
            f"which {self.reachable_orbit_size} fall inside the holder envelope. "
            "Every equivalent gives the same diffraction pattern, so the choice among "
            "them is free; the ranking prefers the shortest, safest, best-conditioned "
            "move."
        )
        if not self.solutions:
            body = (
                " NO SOLUTION is reachable. "
                + (
                    f"The nearest approach is {self.nearest_approach.position}, which "
                    f"leaves {self.nearest_approach.residual_deg:.1f} deg between the "
                    "target and the beam — often still useful, since the Kikuchi pole "
                    "will be visible and can be walked in if the envelope allows."
                    if self.nearest_approach is not None
                    else "No orbit member comes close enough to be useful."
                )
                + " Consider re-mounting the specimen, or a holder with a wider envelope."
            )
        else:
            best = self.solutions[0]
            body = f" Best solution: {best.describe()}"
            if len(self.solutions) > 1:
                alternatives = "; ".join(
                    f"alpha {solution.position.alpha_deg:+.1f} deg, beta "
                    f"{solution.position.beta_deg:+.1f} deg "
                    f"({solution.travel_deg:.0f} deg travel"
                    + (
                        f", hypothesis {solution.family.index}"
                        if solution.family.index != 1
                        else ""
                    )
                    + ")"
                    for solution in self.solutions[1:5]
                )
                body += f" Alternatives: {alternatives}."
        waypoints = ""
        if self.waypoints:
            listed = ", ".join(
                format_direction_indices(_int_list(direction.coordinates))
                for direction in self.waypoints
            )
            waypoints = (
                f" This is a long excursion, so route through intermediate zones and "
                f"re-index at each: {listed}. An error in the diffraction rotation costs "
                "a residual proportional to the length of the hop, so several short hops "
                "with re-indexing are self-correcting where one long hop is open-loop."
            )
        notes = (" " + " ".join(self.notes)) if self.notes else ""
        return head + body + waypoints + notes + " " + self.ambiguity.describe()

    def to_json_dict(self) -> dict[str, Any]:
        """Serializable payload, kept in lockstep with :meth:`describe`."""

        return {
            "schema": "pytex.tilt_plan_report/1",
            "phase": self.current.phase.name,
            "target": [int(value) for value in self.target.indices],
            "tolerance_deg": self.tolerance_deg,
            "is_reachable": self.is_reachable,
            "orbit_size": self.orbit_size,
            "reachable_orbit_size": self.reachable_orbit_size,
            "current": self.current.to_json_dict(),
            "ambiguity": self.ambiguity.to_json_dict(),
            "solutions": [solution.to_json_dict() for solution in self.solutions],
            "nearest_approach": (
                None
                if self.nearest_approach is None
                else self.nearest_approach.to_json_dict()
            ),
            "waypoints": [
                _int_list(direction.coordinates)
                for direction in self.waypoints
            ],
            "notes": list(self.notes),
        }


@lru_cache(maxsize=32)
def _direction_grid(
    lattice_key: tuple[float, ...], max_index: int
) -> tuple[np.ndarray, np.ndarray]:
    """Lattice directions up to ``max_index`` and their unit Cartesian images.

    Cached on the direct-basis matrix because the grid depends only on the
    lattice, and rebuilding it for every candidate solution dominated the
    solver's cost while producing an identical array each time.
    """

    direct = np.asarray(lattice_key, dtype=np.float64).reshape(3, 3)
    values = np.arange(-max_index, max_index + 1, dtype=np.int64)
    grid = np.stack(np.meshgrid(values, values, values, indexing="ij"), axis=-1)
    uvw = grid.reshape(-1, 3)
    uvw = uvw[np.any(uvw != 0, axis=1)]
    images = uvw.astype(np.float64) @ direct.T
    images = images / np.linalg.norm(images, axis=1)[:, None]
    return uvw, images


def _rationalize_direction(
    phase: Phase, cartesian: np.ndarray, *, max_index: int = 6, tolerance_deg: float = 2.0
) -> np.ndarray | None:
    """Nearest low-index lattice direction to a Cartesian crystal-frame vector."""

    direct = phase.lattice.direct_basis().matrix
    uvw, images = _direction_grid(
        tuple(float(value) for value in np.asarray(direct).ravel()), max_index
    )
    cosines = images @ normalize_vector(cartesian)
    deviations = np.degrees(np.arccos(np.clip(cosines, -1.0, 1.0)))
    admissible = deviations <= tolerance_deg
    if not np.any(admissible):
        return None
    candidates = uvw[admissible]
    order = np.lexsort(
        (np.max(np.abs(candidates), axis=1), np.sum(np.abs(candidates), axis=1))
    )
    return np.asarray(candidates[order[0]], dtype=np.int64)


def _orbit_directions(phase: Phase, direction: np.ndarray) -> np.ndarray:
    """Symmetry orbit of a crystal direction, both senses, deduplicated."""

    operators = np.asarray(phase.symmetry.operators, dtype=np.float64)
    images = np.einsum("nij,j->ni", operators, normalize_vector(direction))
    both = np.vstack([images, -images])
    unique: list[np.ndarray] = []
    for row in both:
        if not any(float(np.linalg.norm(row - kept)) < 1e-8 for kept in unique):
            unique.append(row)
    return np.asarray(unique, dtype=np.float64)


def _refine_angles(
    stage: StageModel,
    direction_holder: np.ndarray,
    seed: tuple[float, float],
    *,
    iterations: int = 24,
) -> tuple[float, float]:
    """Gauss-Newton refinement of the stage angles for a non-ideal stage.

    The closed form solves the *ideal* geometry exactly; a calibrated stage with
    a non-orthogonal or mis-set axis pair has no closed form, so the analytic
    solution seeds a small numerical refinement. Two dimensions, a good seed and
    a smooth objective mean this converges in a handful of steps; a failure to
    converge indicates a pathological stage model rather than a numerical
    accident.
    """

    alpha, beta = seed
    step = 1e-5

    def residual(a: float, b: float) -> np.ndarray:
        achieved = stage.rotation_matrix(a, b) @ direction_holder
        return np.asarray(achieved[:2], dtype=np.float64)

    for _ in range(iterations):
        base = residual(alpha, beta)
        if float(np.linalg.norm(base)) < 1e-14:
            break
        jacobian = np.column_stack(
            [
                (residual(alpha + step, beta) - base) / step,
                (residual(alpha, beta + step) - base) / step,
            ]
        )
        try:
            delta = np.linalg.lstsq(jacobian, -base, rcond=None)[0]
        except np.linalg.LinAlgError:  # pragma: no cover - defensive
            break
        alpha += float(delta[0])
        beta += float(delta[1])
    return float(alpha), float(beta)


def _forward_residual_deg(
    stage: StageModel,
    crystal_to_holder: np.ndarray,
    direction_crystal: np.ndarray,
    alpha_deg: float,
    beta_deg: float,
    *,
    allow_reverse: bool,
) -> float:
    """Re-derive the achieved direction and measure its angle from the beam.

    Deliberately recomputes from the crystal direction through the full
    calibrated chain rather than reusing any intermediate the solver produced, so
    that a solver error cannot validate itself.
    """

    achieved = stage.rotation_matrix(alpha_deg, beta_deg) @ crystal_to_holder @ direction_crystal
    cosine = float(np.dot(normalize_vector(achieved), BEAM_AXIS_LABORATORY))
    if allow_reverse:
        cosine = abs(cosine)
    return float(math.degrees(math.acos(max(-1.0, min(1.0, cosine)))))


def plan_tilt_to_zone_axis(
    current: CurrentState,
    target: ZoneAxis | CrystalDirection | ArrayLike,
    stage: StageModel,
    *,
    tolerance_deg: float = DEFAULT_TOLERANCE_DEG,
    allow_reverse: bool = True,
    path_strategy: PathStrategy = PathStrategy.GEODESIC,
    path_samples: int = DEFAULT_PATH_SAMPLES,
    margin_floor_deg: float = DEFAULT_MARGIN_FLOOR_DEG,
    max_solutions: int = 5,
    ranking: RankingWeights = DEFAULT_RANKING,
    include_paths: bool = True,
    provenance: ProvenanceRecord | None = None,
) -> TiltPlanReport:
    """Find the holder tilts that bring a target zone axis onto the beam.

    Purpose
    -------
    The question asked in front of a microscope: *I am down one zone axis and I
    want another — which way do I tilt, how far, and can I even get there?* This
    answers it completely, including the parts an operator cannot check by eye:
    whether a symmetry equivalent is closer, whether the answer depends on a
    calibration that might be stale, and whether the route stays inside the
    holder.

    When to use
    -----------
    After indexing the current pattern and building a :class:`CurrentState`.
    Prefer :meth:`CurrentState.from_two_zone_axes` for that step: it needs no
    diffraction-rotation calibration and is therefore immune to the error mode
    that sends an operator tilting backwards.

    Algorithm
    ---------
    For each ambiguity family and each symmetry-equivalent target direction, the
    holder-frame direction ``w = U t`` is formed and the stage angles follow in
    closed form; a non-ideal stage refines them numerically from that seed. Every
    candidate is then re-derived through the calibrated forward model and
    rejected if its residual exceeds ``tolerance_deg`` — before ranking, not
    after. Survivors are scored on travel, largest single-axis move, envelope
    clearance, propagated uncertainty and conditioning.

    Parameters
    ----------
    current : CurrentState
        The reconstructed crystal-to-holder orientation and stage position.
    target : ZoneAxis, CrystalDirection or array_like
        The wanted zone axis. Integer indices are interpreted in the direct
        lattice basis of the phase.
    stage : StageModel
    tolerance_deg : float, default 0.5
        Largest acceptable forward-validated residual.
    allow_reverse : bool, default True
        Accept the target antiparallel to the beam. A kinematic pattern cannot
        tell the two senses apart, so this is normally what is wanted; set it
        false for polarity-sensitive work, but only when the sense has actually
        been determined.
    path_strategy : PathStrategy, default GEODESIC
    path_samples : int, default 25
    margin_floor_deg : float, default 2
    max_solutions : int, default 5
    ranking : RankingWeights, optional
    include_paths : bool, default True
        Plan a path for each solution. Disable for bulk reachability sweeps.
    provenance : ProvenanceRecord, optional

    Returns
    -------
    TiltPlanReport
        Call :meth:`TiltPlanReport.best` for the recommended move, or
        :meth:`TiltPlanReport.describe` for the whole answer as prose.

    Notes
    -----
    Every solution records the orbit member it actually lands on. All members
    give the same diffraction pattern, but the in-plane azimuth relative to
    specimen features differs, so an operator comparing a boundary trace against
    the pattern should read that field.

    Examples
    --------
    For a cubic crystal oriented with ``[001]`` on the beam at zero tilt, the
    ``[011]`` zone lies 45 degrees away, which is beyond a 30 degree holder — but
    a symmetry equivalent sits inside it, which is exactly the case this
    function exists to find.
    """

    phase = current.phase
    target_zone = _coerce_target(target, phase)
    target_cartesian = normalize_vector(target_zone.unit_vector)
    matrix = current.matrix

    orbit = _orbit_directions(phase, target_cartesian)
    families = current.ambiguity.families

    candidates: list[TiltSolution] = []
    rejected_best: tuple[float, float, float] | None = None
    reachable_members: set[tuple[int, int, int]] = set()

    for family in families:
        family_matrix = matrix @ family.operator
        for member in orbit:
            holder_direction = family_matrix @ member
            for alpha_seed, beta_seed in solve_tilts_for_direction(
                holder_direction, allow_reverse=allow_reverse
            ):
                if stage.calibration.axes.is_ideal:
                    alpha, beta = alpha_seed, beta_seed
                else:
                    alpha, beta = _refine_angles(
                        stage, holder_direction, (alpha_seed, beta_seed)
                    )
                residual = _forward_residual_deg(
                    stage,
                    family_matrix,
                    member,
                    alpha,
                    beta,
                    allow_reverse=allow_reverse,
                )
                # The cheap rejections come first: assembling a solution
                # rationalizes the landed direction against a lattice-index grid,
                # which is far more expensive than either test and is wasted on a
                # candidate that fails one of them.
                if residual > tolerance_deg:
                    continue
                margin = float(stage.envelope.margin_deg(alpha, beta))
                if margin < 0.0:
                    # An exact solution exists but lies outside the envelope.
                    # Kept only to explain *how far* out of range the target is;
                    # it is never offered as a nearest approach, which must by
                    # definition be a position the holder can actually reach.
                    if rejected_best is None or margin > rejected_best[0]:
                        rejected_best = (margin, alpha, beta)
                    continue
                solution = _build_solution(
                    current=current,
                    stage=stage,
                    phase=phase,
                    family=family,
                    member=member,
                    family_matrix=family_matrix,
                    alpha=alpha,
                    beta=beta,
                    residual=residual,
                    margin=margin,
                    tolerance_deg=tolerance_deg,
                    ranking=ranking,
                    target_cartesian=target_cartesian,
                )
                key = _member_key(member)
                reachable_members.add(key)
                candidates.append(solution)

    deduplicated = _deduplicate(candidates)
    deduplicated.sort(key=lambda solution: solution.cost)
    selected = deduplicated[:max_solutions]

    nearest = None
    if not selected:
        nearest = _nearest_approach(
            current, stage, phase, families, orbit, allow_reverse, ranking, tolerance_deg
        )

    if include_paths and selected:
        selected = [
            _attach_path(
                solution,
                current,
                stage,
                phase,
                path_strategy,
                path_samples,
                margin_floor_deg,
            )
            for solution in selected
        ]

    waypoints: tuple[CrystalDirection, ...] = ()
    if selected and selected[0].travel_deg > LONG_HOP_THRESHOLD_DEG:
        waypoints = suggest_waypoints(
            phase,
            current.beam_direction_crystal(stage),
            selected[0].orbit_member,
        )

    notes: list[str] = []
    if not stage.calibration.axes.is_ideal:
        notes.append(
            "The stage axes are non-ideal, so the closed-form solution was refined "
            "numerically through the calibrated model; the reported residual comes "
            "from that model."
        )
    if current.consistency_residual_deg is not None and current.consistency_residual_deg > 2.0:
        notes.append(
            f"WARNING: the reconstruction's interzonal-angle residual is "
            f"{current.consistency_residual_deg:.1f} deg, which is large. Suspect a "
            "reversed stage sign convention, a mis-indexed zone, or a bent specimen "
            "before trusting these tilts."
        )

    return TiltPlanReport(
        solutions=tuple(selected),
        current=current,
        target=target_zone,
        ambiguity=current.ambiguity,
        orbit_size=int(orbit.shape[0]),
        reachable_orbit_size=len(reachable_members),
        nearest_approach=nearest,
        tolerance_deg=tolerance_deg,
        waypoints=waypoints,
        notes=tuple(notes),
        provenance=provenance,
    )


def _coerce_target(
    target: ZoneAxis | CrystalDirection | ArrayLike, phase: Phase
) -> ZoneAxis:
    """Accept a zone axis, a crystal direction, or bare indices."""

    if isinstance(target, ZoneAxis):
        if target.phase != phase:
            raise ValueError(
                "The target ZoneAxis belongs to a different phase than the current state."
            )
        return target
    if isinstance(target, CrystalDirection):
        return ZoneAxis(np.asarray(_int_list(target.coordinates), dtype=np.int64), phase=phase)
    return ZoneAxis(np.rint(np.asarray(target)).astype(np.int64), phase=phase)


def _member_key(member: np.ndarray) -> tuple[int, int, int]:
    """Hashable key identifying an orbit member up to numerical noise."""

    return tuple(round(float(value) * 1e6) for value in member)  # type: ignore[return-value]


def _nearest_score(solution: TiltSolution) -> float:
    """How good a rejected candidate is as a nearest approach."""

    return solution.residual_deg - min(solution.envelope_margin_deg, 0.0)


def _build_solution(
    *,
    current: CurrentState,
    stage: StageModel,
    phase: Phase,
    family: AmbiguityFamily,
    member: np.ndarray,
    family_matrix: np.ndarray,
    alpha: float,
    beta: float,
    residual: float,
    margin: float,
    tolerance_deg: float,
    ranking: RankingWeights,
    target_cartesian: np.ndarray,
) -> TiltSolution:
    """Assemble a candidate solution with its metrics and uncertainties."""

    position = StagePosition(alpha, beta)
    delta_alpha = alpha - current.position.alpha_deg
    delta_beta = beta - current.position.beta_deg
    travel = _rotation_angle_between(
        stage.rotation_matrix(current.position.alpha_deg, current.position.beta_deg),
        stage.rotation_matrix(alpha, beta),
    )
    conditioning = 1.0 / max(math.cos(math.radians(alpha)), 1e-6)

    # Uncertainty: the orientation error and the stage readout error both map
    # into the required angles, amplified by the conditioning factor in beta.
    sigma_input = math.hypot(
        current.orientation_uncertainty_deg, stage.calibration.angular_uncertainty_deg
    )
    sigma_alpha = float(sigma_input * conditioning)
    sigma_beta = float(sigma_input * conditioning)
    sigma_residual = float(
        math.hypot(sigma_input, stage.calibration.backlash_deg)
    )

    achieved = stage.rotation_matrix(alpha, beta) @ family_matrix @ member
    is_reversed = bool(float(np.dot(normalize_vector(achieved), BEAM_AXIS_LABORATORY)) < 0.0)

    verdict = (
        Reachability.EXACT
        if residual <= 1e-6 and margin >= 0.0
        else Reachability.WITHIN_TOLERANCE
        if residual <= tolerance_deg and margin >= 0.0
        else Reachability.UNREACHABLE
    )

    indices = _rationalize_direction(phase, member)
    same_direction = float(np.dot(member, target_cartesian)) > 1.0 - 1e-8
    notes = (
        ("This is the requested direction itself.",)
        if same_direction
        else (
            "This is a symmetry equivalent of the requested direction, not the "
            "direction itself: the diffraction pattern is identical, but the in-plane "
            "azimuth relative to specimen features differs.",
        )
    )

    cost = ranking.cost(
        travel_deg=travel,
        largest_axis_move_deg=max(abs(delta_alpha), abs(delta_beta)),
        margin_deg=margin,
        uncertainty_deg=sigma_residual,
        conditioning=conditioning,
    )
    return TiltSolution(
        position=position,
        verdict=verdict,
        residual_deg=residual,
        orbit_member=member,
        orbit_member_indices=indices,
        family=family,
        is_reversed=is_reversed,
        travel_deg=travel,
        delta_alpha_deg=delta_alpha,
        delta_beta_deg=delta_beta,
        envelope_margin_deg=margin,
        conditioning=conditioning,
        sigma_alpha_deg=sigma_alpha,
        sigma_beta_deg=sigma_beta,
        sigma_residual_deg=sigma_residual,
        cost=cost,
        notes=notes,
    )


def _deduplicate(solutions: list[TiltSolution]) -> list[TiltSolution]:
    """Drop solutions that repeat a stage position within a thousandth of a degree."""

    kept: list[TiltSolution] = []
    for solution in solutions:
        duplicate = any(
            abs(solution.position.alpha_deg - other.position.alpha_deg) < 1e-3
            and abs(solution.position.beta_deg - other.position.beta_deg) < 1e-3
            and solution.family.index == other.family.index
            for other in kept
        )
        if not duplicate:
            kept.append(solution)
    return kept


def _attach_path(
    solution: TiltSolution,
    current: CurrentState,
    stage: StageModel,
    phase: Phase,
    strategy: PathStrategy,
    samples: int,
    margin_floor_deg: float,
) -> TiltSolution:
    """Plan and attach the route to a solution."""

    path = plan_path(
        current.position,
        solution.position,
        stage,
        current.matrix @ solution.family.operator,
        strategy=strategy,
        samples=samples,
        margin_floor_deg=margin_floor_deg,
        phase=phase,
    )
    return TiltSolution(
        position=solution.position,
        verdict=solution.verdict,
        residual_deg=solution.residual_deg,
        orbit_member=solution.orbit_member,
        orbit_member_indices=solution.orbit_member_indices,
        family=solution.family,
        is_reversed=solution.is_reversed,
        travel_deg=solution.travel_deg,
        delta_alpha_deg=solution.delta_alpha_deg,
        delta_beta_deg=solution.delta_beta_deg,
        envelope_margin_deg=solution.envelope_margin_deg,
        conditioning=solution.conditioning,
        sigma_alpha_deg=solution.sigma_alpha_deg,
        sigma_beta_deg=solution.sigma_beta_deg,
        sigma_residual_deg=solution.sigma_residual_deg,
        path=path,
        cost=solution.cost,
        notes=solution.notes,
    )


def _nearest_approach(
    current: CurrentState,
    stage: StageModel,
    phase: Phase,
    families: tuple[AmbiguityFamily, ...],
    orbit: np.ndarray,
    allow_reverse: bool,
    ranking: RankingWeights,
    tolerance_deg: float,
) -> TiltSolution | None:
    """The reachable stage position that comes closest to any orbit member.

    Purpose
    -------
    Answers "how close can I get?" when the answer to "can I get there?" is no.
    A six-degree miss still shows the Kikuchi pole and is frequently useful, so
    reporting the nearest approach is a real answer rather than a consolation.

    Searches the envelope on a grid. The grid step is about a degree, which is
    finer than the residual is ever quoted to, so refining further would report
    precision the answer does not have.
    """

    alpha_min, alpha_max, beta_min, beta_max = stage.envelope.bounds()
    alphas = np.linspace(alpha_min, alpha_max, 91)
    betas = np.linspace(beta_min, beta_max, 91)
    grid_alpha, grid_beta = np.meshgrid(alphas, betas, indexing="ij")
    flat_alpha = grid_alpha.ravel()
    flat_beta = grid_beta.ravel()

    inside = np.fromiter(
        (
            stage.envelope.contains(float(a), float(b))
            for a, b in zip(flat_alpha, flat_beta, strict=True)
        ),
        dtype=bool,
        count=flat_alpha.size,
    )
    if not np.any(inside):
        return None
    flat_alpha = flat_alpha[inside]
    flat_beta = flat_beta[inside]

    # The reachable beam directions, evaluated once and reused for every
    # candidate: the grid does not depend on the target. An ideal stage has a
    # vectorized closed form, which is worth taking because this grid is the
    # largest single computation in the package.
    if stage.calibration.axes.is_ideal and isinstance(stage, DoubleTiltStage):
        beams = beam_direction_holder(flat_alpha, flat_beta)
    else:
        beams = np.stack(
            [
                stage.beam_direction(float(a), float(b))
                for a, b in zip(flat_alpha, flat_beta, strict=True)
            ]
        )

    best: tuple[float, float, float, np.ndarray, AmbiguityFamily] | None = None
    for family in families:
        family_matrix = current.matrix @ family.operator
        directions = np.einsum("ij,nj->ni", family_matrix, orbit)
        cosines = beams @ directions.T
        if allow_reverse:
            cosines = np.abs(cosines)
        angles = np.degrees(np.arccos(np.clip(cosines, -1.0, 1.0)))
        flat_index = int(np.argmin(angles))
        grid_index, member_index = np.unravel_index(flat_index, angles.shape)
        angle = float(angles[grid_index, member_index])
        if best is None or angle < best[0]:
            best = (
                angle,
                float(flat_alpha[grid_index]),
                float(flat_beta[grid_index]),
                orbit[member_index],
                family,
            )

    if best is None:
        return None
    residual, alpha, beta, member, family = best
    solution = _build_solution(
        current=current,
        stage=stage,
        phase=phase,
        family=family,
        member=member,
        family_matrix=current.matrix @ family.operator,
        alpha=alpha,
        beta=beta,
        residual=residual,
        margin=float(stage.envelope.margin_deg(alpha, beta)),
        tolerance_deg=tolerance_deg,
        ranking=ranking,
        target_cartesian=member,
    )
    return TiltSolution(
        position=solution.position,
        verdict=Reachability.NEAREST_APPROACH,
        residual_deg=solution.residual_deg,
        orbit_member=solution.orbit_member,
        orbit_member_indices=solution.orbit_member_indices,
        family=solution.family,
        is_reversed=solution.is_reversed,
        travel_deg=solution.travel_deg,
        delta_alpha_deg=solution.delta_alpha_deg,
        delta_beta_deg=solution.delta_beta_deg,
        envelope_margin_deg=solution.envelope_margin_deg,
        conditioning=solution.conditioning,
        sigma_alpha_deg=solution.sigma_alpha_deg,
        sigma_beta_deg=solution.sigma_beta_deg,
        sigma_residual_deg=solution.sigma_residual_deg,
        cost=solution.cost,
        notes=(
            "Nearest approach: no orbit member is reachable exactly, and this is the "
            "closest the holder can come. The target pole will be off-axis by the "
            "residual angle, which is often still enough to see and work with.",
        ),
    )


def _rotation_angle_between(first: np.ndarray, second: np.ndarray) -> float:
    """Angle of the rotation carrying ``first`` onto ``second``, in degrees."""

    relative = second @ first.T
    trace = float(np.trace(relative))
    return float(math.degrees(math.acos(max(-1.0, min(1.0, (trace - 1.0) / 2.0)))))
