function [CS, SS] = mtex_phase_symmetry(phase)
%MTEX_PHASE_SYMMETRY Construct MTEX crystal/specimen symmetries from shared JSON phase.
lp = phase.lattice_parameters;
CS = crystalSymmetry( ...
    string(phase.point_group), ...
    [lp.a, lp.b, lp.c], ...
    [lp.alpha, lp.beta, lp.gamma] * degree, ...
    "mineral", string(phase.phase_id));
SS = specimenSymmetry("1");
end

